# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/data/ImageData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf.common import messageData_pb2 as protobuf_dot_common_dot_messageData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/data/ImageData.proto',
  package='protobuf.data',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dprotobuf/data/ImageData.proto\x12\rprotobuf.data\x1a!protobuf/common/messageData.proto\"~\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\r\n\x05\x66rame\x18\x04 \x01(\x03\x12\x33\n\r_message_data\x18\x05 \x01(\x0b\x32\x1c.protobuf.common.messageDatab\x06proto3')
  ,
  dependencies=[protobuf_dot_common_dot_messageData__pb2.DESCRIPTOR,])




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='protobuf.data.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='protobuf.data.Image.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='protobuf.data.Image.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='protobuf.data.Image.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame', full_name='protobuf.data.Image.frame', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_message_data', full_name='protobuf.data.Image._message_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=209,
)

_IMAGE.fields_by_name['_message_data'].message_type = protobuf_dot_common_dot_messageData__pb2._MESSAGEDATA
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'protobuf.data.ImageData_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.data.Image)
  ))
_sym_db.RegisterMessage(Image)


# @@protoc_insertion_point(module_scope)
