# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/common/Boolean.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/common/Boolean.proto',
  package='protobufs.common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dprotobuf/common/Boolean.proto\x12\x10protobufs.common\"\x18\n\x07\x42oolean\x12\r\n\x05value\x18\x01 \x01(\x08\x62\x06proto3')
)




_BOOLEAN = _descriptor.Descriptor(
  name='Boolean',
  full_name='protobufs.common.Boolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protobufs.common.Boolean.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Boolean'] = _BOOLEAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Boolean = _reflection.GeneratedProtocolMessageType('Boolean', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEAN,
  __module__ = 'protobuf.common.Boolean_pb2'
  # @@protoc_insertion_point(class_scope:protobufs.common.Boolean)
  ))
_sym_db.RegisterMessage(Boolean)


# @@protoc_insertion_point(module_scope)
